connector:
  format: json
  routing:
    topic: site_tracking
    mode: static
  kafka:
    bootstrapServers:
      - localhost:9092
    producerPoolSize: 1
  ticker:
    enabled: true
    period: 10s